'use client';

import Link from 'next/link';
import { 
  Sparkles,Camera,ListOrdered,Lightbulb,Search,Smartphone,Monitor,ArrowLeft
} from 'lucide-react';

export default function AiLearningPage() {
  const features = [
    {
      icon: Camera,
      title: 'Snap & Upload',
      desc: 'Stuck on a complex math problem? Just take a picture or upload a screenshot of the question.',
      color: 'bg-blue-100 text-blue-600',
    },
    {
      icon: ListOrdered,
      title: 'Step-by-Step Breakdown',
      desc: 'Our AI doesn’t just give you the final answer. It breaks the solution down into easy-to-understand, logical steps.',
      color: 'bg-indigo-100 text-indigo-600',
    },
    {
      icon: Lightbulb,
      title: 'Hints & Dedicated Examples',
      desc: 'Get gentle nudges in the right direction and see similar examples to understand the core concept better.',
      color: 'bg-amber-100 text-amber-600',
    },
    {
      icon: Search,
      title: 'Find Similar Questions',
      desc: 'Master the topic by instantly searching for and practicing similar questions generated by the AI.',
      color: 'bg-emerald-100 text-emerald-600',
    }
  ];

  return (
    <main className="min-h-screen bg-slate-50 font-sans selection:bg-blue-200">
      
      {/* Top Navigation Bar */}
      <div className="max-w-5xl mx-auto px-4 py-6 md:px-8">
        <Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-slate-900 transition-colors">
          <ArrowLeft className="w-4 h-4" /> Back to Home
        </Link>
      </div>

      <div className="max-w-5xl mx-auto px-4 pb-20 md:px-8">
        
        <div className="text-center py-12 md:py-16 relative">
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-3/4 h-3/4 bg-blue-400/20 blur-[100px] rounded-full pointer-events-none"></div>
          
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-blue-50 border border-blue-100 text-blue-700 font-bold text-sm mb-6 relative z-10">
            <Sparkles className="w-4 h-4" /> Next-Gen Learning
          </div>
          
          <h1 className="text-4xl md:text-6xl font-black text-slate-900 tracking-tight mb-6 relative z-10">
            Master Any Subject with <br className="hidden md:block" />
            <span className="text-transparent bg-clip-text bg-linear-to-r from-blue-600 to-indigo-600">
              AI-Powered Assistance
            </span>
          </h1>
          
          <p className="text-lg md:text-xl text-slate-600 max-w-2xl mx-auto font-medium relative z-10">
            Don't just find the answer—understand the process. Upload any question and let our AI guide you to the solution step-by-step.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 md:gap-8 mb-20 relative z-10">
          {features.map((feature, idx) => {
            const Icon = feature.icon;
            return (
              <div key={idx} className="bg-white p-8 rounded-4xl shadow-sm border border-slate-200 hover:shadow-lg hover:-translate-y-1 transition-all duration-300">
                <div className={`w-14 h-14 rounded-2xl flex items-center justify-center mb-6 ${feature.color}`}>
                  <Icon className="w-7 h-7" strokeWidth={2.5} />
                </div>
                <h3 className="text-xl font-bold text-slate-800 mb-3">{feature.title}</h3>
                <p className="text-slate-600 leading-relaxed">{feature.desc}</p>
              </div>
            );
          })}
        </div>

        <div className="bg-slate-900 rounded-[2.5rem] p-8 md:p-12 shadow-2xl relative overflow-hidden">
          <div className="absolute -top-24 -right-24 w-64 h-64 bg-indigo-500/30 blur-[80px] rounded-full pointer-events-none"></div>
          <div className="absolute -bottom-24 -left-24 w-64 h-64 bg-blue-500/30 blur-[80px] rounded-full pointer-events-none"></div>

          <div className="relative z-10 text-center mb-10">
            <h2 className="text-3xl md:text-4xl font-black text-white mb-4">Experience it Anywhere</h2>
            <p className="text-slate-400 max-w-xl mx-auto text-lg">
              Seamlessly sync your learning journey across your devices.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 relative z-10 max-w-4xl mx-auto">
            
            <div className="bg-white/10 backdrop-blur-md border border-white/20 p-8 rounded-3xl flex flex-col items-center text-center">
              <div className="w-16 h-16 rounded-full bg-blue-500 flex items-center justify-center mb-6 shadow-[0_0_30px_rgba(59,130,246,0.5)]">
                <Smartphone className="w-8 h-8 text-white" />
              </div>
              <h3 className="text-2xl font-bold text-white mb-2">Mobile App</h3>
              <div className="inline-block px-3 py-1 bg-emerald-500/20 border border-emerald-500/50 text-emerald-400 text-xs font-bold uppercase tracking-wider rounded-full mb-4">
                Available Now
              </div>
              <p className="text-slate-300 mb-8 grow">
                Snap photos of questions directly from your textbook and get instant AI assistance on the go.
              </p>
              <a href="https://play.google.com/store/apps/details?id=com.app.iblib" className="w-full py-3.5 bg-white text-slate-900 font-bold rounded-xl hover:bg-slate-100 transition-colors">
                Download App
              </a>
            </div>

            <div className="bg-slate-800/50 border border-slate-700 p-8 rounded-3xl flex flex-col items-center text-center relative overflow-hidden">
              <div className="absolute inset-0 bg-[repeating-linear-gradient(45deg,transparent,transparent_10px,rgba(255,255,255,0.03)_10px,rgba(255,255,255,0.03)_20px)] pointer-events-none"></div>
              
              <div className="w-16 h-16 rounded-full bg-slate-700 flex items-center justify-center mb-6 relative z-10">
                <Monitor className="w-8 h-8 text-slate-400" />
              </div>
              <h3 className="text-2xl font-bold text-white mb-2 relative z-10">Web App</h3>
              <div className="inline-block px-3 py-1 bg-amber-500/20 border border-amber-500/50 text-amber-400 text-xs font-bold uppercase tracking-wider rounded-full mb-4 relative z-10">
                Coming Soon
              </div>
              <p className="text-slate-400 mb-8 grow relative z-10">
                Upload screenshots, type out complex queries, and enjoy a distraction-free, large-screen learning environment.
              </p>
              <button disabled className="w-full py-3.5 bg-slate-700 text-slate-400 font-bold rounded-xl cursor-not-allowed relative z-10 border border-slate-600">
                Join Web Waitlist
              </button>
            </div>

          </div>
        </div>

      </div>
    </main>
  );
}